version: '3.5'

services:

  server:
    image: node:10.0.0
    user: 1000:1000
    working_dir: /app
    command: yarn start
    ports:
      - 8080:8080
    volumes:
      - ./:/app

  build:
    image: node:10.0.0
    user: 1000:1000
    working_dir: /app
    command: yarn build
    volumes:
      - ./:/app

  yarn:
    image: node:10.0.0
    user: 1000:1000
    working_dir: /app
    entrypoint: yarn
    volumes:
      - ./:/app