import webpack from 'webpack'
import { resolve } from 'path'
import Html from 'html-webpack-plugin'
import Clean from 'clean-webpack-plugin'

const plug = (...plugins: any[]): any[] => plugins.filter(plugin => plugin)

interface Environment {
  production: boolean,
  development: boolean
}

export default ({ production, development }: Environment): webpack.Configuration => ({
  mode: production ? 'production' : 'development',

  target: 'web',

  entry: {
    index: resolve('src', 'index.tsx'),
  },

  output: {
    filename: production ? '[chunkhash].js' : '[name].js',
    chunkFilename: production ? '[chunkhash].js' : '[name].js',
    path: resolve('public')
  },

  module: {
    rules: [{
      test: /\.tsx?$/,
      exclude: /node_modules/,
      loader: 'ts-loader'
    }, {
      test: /\.sass$/,
      use: [
        'style-loader',
        'css-loader',
        'sass-loader'
      ]
    }]
  },

  plugins: plug(
    production && new Clean([
      resolve('public')
    ]),

    new Html({
      template: resolve('src', 'index.html'),
      inject: 'head',

      minify: {
        caseSensitive: false,
        collapseBooleanAttributes: production,
        collapseInlineTagWhitespace: production,
        collapseWhitespace: production,
        conservativeCollapse: false,
        decodeEntities: production,
        html5: true,
        includeAutoGeneratedTags: false,
        keepClosingSlash: development,
        minifyCSS: production,
        minifyJS: production,
        minifyURLs: production,
        preserveLineBreaks: false,
        preventAttributesEscaping: development,
        processConditionalComments: production,
        quoteCharacter: "'",
        removeAttributeQuotes: production,
        removeComments: production,
        removeEmptyAttributes: false,
        removeEmptyElements: false,
        removeOptionalTags: production,
        removeRedundantAttributes: production,
        removeScriptTypeAttributes: production,
        removeStyleLinkTypeAttributes: production,
        removeTagWhitespace: false,
        sortAttributes: production,
        sortClassName: production,
        trimCustomFragments: false,
        useShortDoctype: false
      }
    })
  ),

  devServer: {
    contentBase: resolve('public'),
    watchContentBase: true,
    overlay: true,
    host: '0.0.0.0',
    port: 8080,
    compress: true,
    historyApiFallback: true,
    inline: true
  }
})